load("C:\Users\mperuzzo\OneDrive - Nexus365\Documents\bottlenecks\generated_data\maize_av_ 100 av_ kpp_ 2026-06-10_10-37.mat")

options = optimoptions('fminunc', ...
            'Display', 'iter', ...
            'Algorithm', 'trust-region', ...
            'HessianFcn','objective', ...
            'SpecifyObjectiveGradient',true, ...
            'StepTolerance', 5e-3, ...,
            "FiniteDifferenceStepSize", 0.005, ...,
            "FunctionTolerance",0.00001, ...
            "OptimalityTolerance",2e-6, ...
            'MaxFunctionEvaluations', 10000, ...
            'MaxIterations', 10000, ...
            'OutputFcn', @saveIterations, ... % Call the custom function
            "UseParallel", false);

options = optimoptions('fminunc', ...
            'Display', 'iter', ...
            'Algorithm', 'trust-region', ...
            'HessianFcn','objective', ...
            'SpecifyObjectiveGradient',true, ...
            "OptimalityTolerance",2e-5);

objective_function = @(theta) optimize_model(theta_start, parameters, factor, "kpp");
[theta, fval, exitflag, output, grad, hessian] = fminunc(objective_function, theta_start,options)